fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    resource: "@SbtmBundle/Resources/config/routing.yml"

login_home:
    pattern:   /
    defaults:  { _controller: SbtmappSbtmBundle:Default:summary }
    requirements:
        _method:  GET

sbtm_summary:
    pattern:   /summary
    defaults:  { _controller: SbtmappSbtmBundle:Default:summary }
    requirements:
        _method:  GET