fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


login_home:
    pattern:   /
    defaults:  { _controller: SbtmappSbtmBundle:Default:summary }
    requirements:
        _method:  GET

SbtmappSbtmBundle_summary:
    pattern:   /summary
    defaults:  { _controller: SbtmappSbtmBundle:Default:summary }
    requirements:
        _method:  GET|POST
        
SbtmappSbtmBundle_about:
    pattern:  /about
    defaults: { _controller: SbtmappSbtmBundle:Default:about }
    requirements:
        _method:  GET
        
SbtmappSbtmBundle_sessions:
    pattern:  /sessions
    defaults: { _controller: SbtmappSbtmBundle:Default:sessions }
    requirements:
        _method:  GET